/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Package.Interface;

import Package.Sockets.Vol;


/**
 *
 * @author Cynthia Abou Maroun
 */

public class VolInterface extends javax.swing.JFrame 
{

    /**
     * Creates new form VolIntrface
     */
    
    Vol _Vol = null;

    public VolInterface() 
    {
        initComponents();
        this.setTitle("Interface: Vol");
        this.setSize(1800, 1200);
        this.setLocationRelativeTo(null);
        _Vol = new Vol(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ColorChooser = new javax.swing.JColorChooser();
        ScrollPane = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        TextArea.setEditable(false);
        TextArea.setColumns(21);
        TextArea.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        TextArea.setForeground(new java.awt.Color(204, 204, 255));
        TextArea.setRows(6);
        TextArea.setTabSize(9);
        ScrollPane.setViewportView(TextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1026, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if (_Vol != null) 
        {
            _Vol._Fonction.CloseConnexion();
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) 
    {
        
//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try         
        {
        /* Set the Nimbus look and feel */

            for (javax.swing.UIManager.LookAndFeelInfo Info : javax.swing.UIManager.getInstalledLookAndFeels()) 
            {
                if ("Nimbus".equals(Info.getName())) 
                {
                    javax.swing.UIManager.setLookAndFeel(Info.getClassName());
                    break;
                }
            }
        } 
        catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException e) 
        {
            System.out.println(e);
            System.out.println("Java L&F: Look and Feel Exceptiom error!!!");
            System.out.println(VolInterface.class.getName());
        }
//</editor-fold>
        
        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(() -> {new VolInterface().setVisible(true);});
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JColorChooser ColorChooser;
    private javax.swing.JScrollPane ScrollPane;
    public javax.swing.JTextArea TextArea;
    // End of variables declaration//GEN-END:variables
}
